version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - DOCKER_BUILDKIT=0  # Disable BuildKit for this service

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 6AVA9RtZD9F3gfTv
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - DOCKER_BUILDKIT=0  # Disable BuildKit for this service
      - MONGODB_URI=mongodb+srv://admin:6AVA9RtZD9F3gfTv@cluster0.myynpss.mongodb.net/?retryWrites=true&w=majority

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  mongodb_data:
